Rename `tsc`'s `--out` flag to `--outFile`
Fixes:

```
❯ make
GOPATH=/home/vterron/code/go/.build go get github.com/a-urth/go-bindata/...
tsc --out /tmp/tmp.M88D2Or76Y web/assets/edit.ts
error TS5101: Option 'out' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'outFile' instead.

Found 1 error.

make: *** [Makefile:19: .build/assets/edit.js] Error 2
```